[package]
name = "wasm_basic"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"
strip = "debuginfo"
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
theus = { path = "../.." }
